KEY_NODENAME = "nN"
KEY_ATTRIBUTENAME = "aN"
KEY_ATTRIBUTEVALUE = "aV"
KEY_SRC_ATTRIBUTENAME = "srcAN"
KEY_SRC_ATTRIBUTEVALUE = "srcAV"
KEY_VAILIDITYNODES = "dn"
KEY_DEFAULTVALUE = 'dv'

KEY_VALIDATOR_NAME = "vN"
KEY_VALIDATOR_SOURCENODES = "vSN"
