KEY_NODENAME = "nN"
KEY_NODTYPE = "nT"
KEY_DEST_ATTRIBUTENAME = "aN"
KEY_DEST_ATTRIBUTEVALUE = "aV"
KEY_SRC_ATTRIBUTENAME = "srcAN"
KEY_SRC_ATTRIBUTEVALUE = "srcAV"
KEY_VAILIDITYNODES = "vdn"
KEY_DEFAULTVALUE = 'dv'

KEY_VALIDATOR_NAME = "vN"
KEY_VALIDATOR_NODES = "vNodes"

NT_VALIDATIONNODE = 0
NT_SOURCENODE = 10
NT_CONNECTIONVALIDITY = 20
NT_DEFAULTVALUE = 30

