#  Copyright (c) 2019.  James Dunlop

# General Nodes
KEY_NODENAME = "nN"
KEY_NODELONGNAME = "nLN"
KEY_NODEDISPLAYNAME = "nDN"
KEY_NODENAMESPACE = "nNS"

KEY_NODETYPE = "nT"

# Connection node
KEY_CONNDATA = "cND"

# Validator
KEY_VALIDATOR_NAME = "vN"
KEY_VALIDATOR_NODES = "vNodes"
KEY_VALIDATORNAMESPACE = "vNS"
KEY_VAILIDITYNODES = "vdn"
KEY_DEFAULTVALUEDATA = "dvD"

# Node types
NT_VALIDATIONNODE = 0
NT_SOURCENODE = 10
NT_CONNECTIONVALIDITY = 20
NT_DEFAULTVALUE = 30
